#define HYDRO_MESHLESS_FINITE_MASS
#define BOX_PERIODIC
#define BOX_LONG_X 16
#define BOX_LONG_Y 1
#define BOX_LONG_Z 1
#define BOX_SPATIAL_DIMENSION 2
#define EOS_GAMMA (2.0)
#define MAGNETIC
#define SELFGRAVITY_OFF
#define OUTPUT_IN_DOUBLEPRECISION
