# SPH profile used to compile and exercise the shared hydro timestep path.
HYDRO_SPH
BOX_SPATIAL_DIMENSION=1
BOX_PERIODIC
SELFGRAVITY_OFF
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
EOS_GAMMA=(5.0/3.0)
